name: Github releases

permissions:
  contents: write

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Release
        uses: softprops/action-gh-release@v1
