name: Webhook

on:
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.TEST_CBC_GEM_GENERIC_WEBHOOK }}
