name: Webhook

on:
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.TEST_CBC_GEM_GENERIC_WEBHOOK }}
          webhook_secret: ""
